import os
import logging
import subprocess
from string import Template
from .models import DebriSolverSystem
from .utils import GMAT_OUT_DIR

logger = logging.getLogger("msv_mem.gmat_driver")

# GMAT R2025a template with specific forces, integrator, and parameters
GMAT_TEMPLATE = """% GMAT R2025a script for MSV-MEM DebriSolver Architecture
% Automatically generated by msv_mem.gmat_driver

Create Spacecraft MSV;
MSV.DryMass = ${MSV_DRY_MASS};
MSV.TotalMass = ${MSV_LAUNCH_MASS};

Create Spacecraft MEM1;
MEM1.DryMass = ${MEM_DRY_MASS};
MEM1.TotalMass = ${MEM_WET_MASS};

% Propulsion Setup
Create ChemicalThruster MSV_Chem;
MSV_Chem.C1 = 1000; % Placeholder thrust
MSV_Chem.Isp = 320; % Typical chem Isp

Create ElectricThruster MEM_EP;
MEM_EP.ConstantThrust = 0.15;
MEM_EP.Isp = ${MEM_EP_ISP};

% Force Model Setup
Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.PointMasses = {Sun, Luna}; % Third-Body Forces
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = On; % Solar Radiation Pressure Active
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof'; % JGM-2 Model

% Integrator Setup
Create PrinceDormand853 DefaultProp_Integrator;
DefaultProp_Integrator.InitialStepSize = 60;
DefaultProp_Integrator.Accuracy = 9.999999999999999e-12;
DefaultProp_Integrator.MinStep = 0.001;
DefaultProp_Integrator.MaxStep = 2700;
DefaultProp_Integrator.MaxStepAttempts = 50;

% Propagator
Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = PrinceDormand853;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;

% Orbits
Create Orbit GTO_Orbit;
GTO_Orbit.SMA = 24505.5;
GTO_Orbit.ECC = 0.7305;
GTO_Orbit.INC = 28.5;

BeginMissionSequence;
MSV.Propagate = DefaultProp(GTO_Orbit);
Report 'GMAT run completed for MSV-MEM DebriSolver Architecture';
EndMissionSequence;
"""

class GMATDriver:
    def __init__(self, system: DebriSolverSystem):
        self.system = system
        
    def write_script(self, filename: str = "complete_mission.gmat"):
        """Generates the GMAT script with substituted parameters."""
        GMAT_OUT_DIR.mkdir(parents=True, exist_ok=True)
        script_path = GMAT_OUT_DIR / filename
        
        params = {
            "MSV_DRY_MASS": self.system.msv.dry_mass,
            "MSV_LAUNCH_MASS": self.system.msv.launch_mass,
            "MEM_WET_MASS": self.system.mem.wet_mass,
            "MEM_DRY_MASS": self.system.scenario_a.dry_mass_margin, # Approximate dry mass
            "MEM_EP_ISP": self.system.mem.ep_isp,
        }
        
        template = Template(GMAT_TEMPLATE)
        script_content = template.safe_substitute(params)
        
        with open(script_path, "w") as f:
            f.write(script_content)
            
        logger.info(f"GMAT script written to {script_path}")
        return script_path

    def run_script(self, script_path):
        """Attempts to execute the GMAT script."""
        gmat_exec = os.environ.get("GMAT_EXEC", "")
        if not gmat_exec:
            logger.warning("GMAT_EXEC environment variable not set. Cannot automatically run GMAT.")
            logger.info(f"Please open and execute the generated script manually: {script_path.resolve()}")
            return False
            
        cmd = [gmat_exec, str(script_path.resolve())]
        logger.info(f"Launching GMAT: {' '.join(cmd)}")
        try:
            subprocess.run(cmd, check=True)
            logger.info("GMAT execution completed successfully.")
            return True
        except subprocess.CalledProcessError as e:
            logger.error(f"GMAT execution failed with exit code {e.returncode}")
            return False
        except FileNotFoundError:
            logger.error(f"GMAT executable not found at {gmat_exec}")
            return False
